from typing import Protocol
from app.core.models import Concept

class KnowledgeGraph(Protocol):
    def upsert_concept(self, concept: Concept) -> None: ...
    def add_edge(self, source: str, relation: str, target: str) -> None: ...

class VectorStore(Protocol):
    def upsert(self, document_id: str, text: str, metadata: dict[str,str]) -> None: ...
    def search(self, query: str, limit: int=5) -> list[dict[str,object]]: ...
